export const BASE_URL = 'http://api.movies.tatiana.nomoredomains.icu';
export const AUTH_BASE_URL = 'http://api.movies.tatiana.nomoredomains.icu';
export const MOVIES_BASE_URL = 'https://api.nomoreparties.co';
export const DEFAULT_TRAILER_LINK ='https://www.youtube.com/watch?v=5qap5aO4i9A';
export const SHORT_MOVIE_DURATION = 40;
export const SMALL_SCREEN_MOVIE_DEFAULT_QTY = 5;
export const MEDIUM_SCREEN_MOVIE_DEFAULT_QTY = 8;
export const BIG_SCREEN_MOVIE_DEFAULT_QTY = 12;
export const BIG_SCREEN_MOVIE_LOAD_MORE_QTY = 4;
export const MEDIUM_SMALL_SCREEN_MOVIE_LOAD_MORE_QTY = 2;
